/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iHungryBurgerShop;

/**
 *
 * @author Shameel Shajaad
 */
import iHungryBurgerShop.RoundedButton;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrderPage
     */
    static Node first;
    private static Node last;

    public static void setfirstNode(Node first) {
        HomePage.first = first;
    }

    public static Node getLastNode() {
        return last;
    }

    public static void setLastNode(Node last) {
        HomePage.last = last;
    }

    public static void setLastNodeNext(Node next) {
        HomePage.last.next = next;
    }

    public static void saveOrdersToFile() {

    }

    public HomePage() {
        initComponents();

        if (first == null) {
            int count = 0;

            try {
                BufferedReader br = new BufferedReader(new FileReader("Burger.txt"));
                String line;
                boolean bool = true;

                while ((line = br.readLine()) != null) {
                    String Order[] = line.split(",");

                    BurgerOrder tempOrder = new BurgerOrder();

                    tempOrder.setBurgerID(Order[0]);
                    tempOrder.setCustomerID(Order[1]);
                    tempOrder.setCustomerName(Order[2]);
                    tempOrder.setBurgerQty(Integer.parseInt(Order[3]));
                    tempOrder.setTotal(Double.parseDouble(Order[4]));
                    tempOrder.setStatus(Integer.parseInt(Order[5]));

                    if (count == 0) {
                        Node n1 = new Node(tempOrder);
                        first = n1;
                        last = n1;
                        count++;
                    } else {
                        Node n1 = new Node(tempOrder);
                        last.next = n1;
                        last = n1;
                    }
                }

                if (bool) {

                }
            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        placeOrderBtn = new javax.swing.JButton();
        searchBestCustomerBtn = new javax.swing.JButton();
        searchOrderBtn = new javax.swing.JButton();
        searchCustomerBtn = new javax.swing.JButton();
        viewOrdersBtn = new javax.swing.JButton();
        updateOrderDetailsBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Burger_Logo.png"))); // NOI18N
        imageLabel.setOpaque(true);

        rightPanel.setBackground(new java.awt.Color(153, 153, 153));

        placeOrderBtn.setBackground(new java.awt.Color(150, 142, 126));
        placeOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        placeOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        placeOrderBtn.setText("Place Order");
        placeOrderBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        placeOrderBtn = new RoundedButton("Place Order");
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });

        searchBestCustomerBtn.setBackground(new java.awt.Color(150, 142, 126));
        searchBestCustomerBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        searchBestCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBestCustomerBtn.setText("Search Best Customer");
        searchBestCustomerBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchBestCustomerBtn.setBorderPainted(false);
        searchBestCustomerBtn = new RoundedButton("Search Best Customer");
        searchBestCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBestCustomerBtnActionPerformed(evt);
            }
        });

        searchOrderBtn.setBackground(new java.awt.Color(150, 142, 126));
        searchOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        searchOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchOrderBtn.setText("Search Order");
        searchOrderBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchOrderBtn.setBorderPainted(false);
        searchOrderBtn = new RoundedButton("Search Order");
        searchOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOrderBtnActionPerformed(evt);
            }
        });

        searchCustomerBtn.setBackground(new java.awt.Color(150, 142, 126));
        searchCustomerBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        searchCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchCustomerBtn.setText("Search Customer");
        searchCustomerBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchCustomerBtn.setBorderPainted(false);
        searchCustomerBtn = new RoundedButton("Search Customer");
        searchCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerBtnActionPerformed(evt);
            }
        });

        viewOrdersBtn.setBackground(new java.awt.Color(150, 142, 126));
        viewOrdersBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        viewOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewOrdersBtn.setText("View Orders");
        viewOrdersBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        viewOrdersBtn.setBorderPainted(false);
        viewOrdersBtn = new RoundedButton("View Orders");
        viewOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersBtnActionPerformed(evt);
            }
        });

        updateOrderDetailsBtn.setBackground(new java.awt.Color(150, 142, 126));
        updateOrderDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        updateOrderDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateOrderDetailsBtn.setText("Update Order Details");
        updateOrderDetailsBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateOrderDetailsBtn.setBorderPainted(false);
        updateOrderDetailsBtn = new RoundedButton("Update Order Details");
        updateOrderDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderDetailsBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(150, 142, 126));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exitBtn.setBorderPainted(false);
        exitBtn = new RoundedButton("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(updateOrderDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchBestCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(placeOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(placeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBestCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateOrderDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBestCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBestCustomerBtnActionPerformed
        new SearchBestCustomerPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_searchBestCustomerBtnActionPerformed

    private void searchOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOrderBtnActionPerformed
        new SearchOrderPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_searchOrderBtnActionPerformed

    private void searchCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerBtnActionPerformed
        new SearchCustomerPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_searchCustomerBtnActionPerformed

    private void viewOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersBtnActionPerformed
        new ViewOrdersPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_viewOrdersBtnActionPerformed

    private void updateOrderDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderDetailsBtnActionPerformed
        new UpdateOrderPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_updateOrderDetailsBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        FileWriter file;

        try {
            file = new FileWriter("Burger.txt", false);
            Node temp = HomePage.first;

            while (temp != null) {
                file.write(temp.order.getBurgerID() + "," + temp.order.getCustomerID() + "," + temp.order.getCustomerName() + "," + temp.order.getBurgerQty() + "," + temp.order.getTotal() + "," + temp.order.getStatus() + "\n");
                temp = temp.next;
            }

            file.close();

        } catch (IOException ex) {

        }

        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed
        new PlaceOrderPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_placeOrderBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton searchBestCustomerBtn;
    private javax.swing.JButton searchCustomerBtn;
    private javax.swing.JButton searchOrderBtn;
    private javax.swing.JButton updateOrderDetailsBtn;
    private javax.swing.JButton viewOrdersBtn;
    // End of variables declaration//GEN-END:variables
}
