/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iHungryBurgerShop;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shameel Shajaad
 */
public class SearchOrderPage extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrderPage
     */
    public SearchOrderPage() {
        initComponents();

        txtOrderID.setText("B");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblTotalText = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerIDSearch = new javax.swing.JLabel();
        lblCustomerNameSearch = new javax.swing.JLabel();
        lblQtySearch = new javax.swing.JLabel();
        lblTotalSearch = new javax.swing.JLabel();
        lblStatusSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 142, 126));

        lblHeader.setBackground(new java.awt.Color(255, 51, 51));
        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("SEARCH ORDER DETAILS");
        lblHeader.setToolTipText("");
        lblHeader.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        lblOrderID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblOrderID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID.setText("Enter Order ID :");

        lblCustomerID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblCustomerID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerID.setText("Customer ID :");

        txtOrderID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        txtOrderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrderIDKeyReleased(evt);
            }
        });

        cancelBtn = new RoundedButton("");
        cancelBtn.setBackground(new java.awt.Color(255, 51, 51));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Back");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQty.setText("Burger QTY :");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Order Status :");

        lblTotalText.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblTotalText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalText.setText("Total :");

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerName.setText("Customer Name :");

        lblCustomerIDSearch.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblCustomerIDSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblCustomerNameSearch.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblCustomerNameSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblQtySearch.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblQtySearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblTotalSearch.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblTotalSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblStatusSearch.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblStatusSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomerID)
                            .addComponent(lblCustomerName)
                            .addComponent(lblQty)
                            .addComponent(lblTotalText)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCustomerIDSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(lblCustomerNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(lblQtySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(lblTotalSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(lblStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void txtOrderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrderIDKeyReleased
        if ((txtOrderID.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Order ID cannot be empty");
            txtOrderID.setText("B");
        }
        if ((txtOrderID.getText().charAt(0)) != 'B') {
            JOptionPane.showMessageDialog(this, "Order ID must start with 'B'");
            txtOrderID.setText("B");
            return;
        }
        String orderID = txtOrderID.getText();

        for (int i = 1; i < orderID.length(); i++) {
            if (orderID.charAt(i) > '9' || orderID.charAt(i) < '0') {
                JOptionPane.showMessageDialog(this, "Invalid Character '" + (orderID.charAt(i)) + "'");
                txtOrderID.setText("B");
            }
        }
        if (orderID.length() > 5) {
            JOptionPane.showMessageDialog(this, "Invalid Order ID length");
            txtOrderID.setText("B");
            return;
        }

        if (orderID.length() == 5) {
            Node temp = HomePage.first;

            boolean bool = true;

            while (temp != null) {
                if (orderID.equals(temp.order.getBurgerID())) {
                    lblCustomerIDSearch.setText(temp.order.getCustomerID());
                    lblCustomerNameSearch.setText(temp.order.getCustomerName());
                    lblQtySearch.setText(Integer.toString(temp.order.getBurgerQty()));
                    lblTotalSearch.setText(Double.toString(temp.order.getTotal()));
                    switch (temp.order.getStatus()) {
                        case 0:
                            lblStatusSearch.setText("PREPARING");
                            break;
                        case 1:
                            lblStatusSearch.setText("DELIVERED");
                            break;
                        case 2:
                            lblStatusSearch.setText("CANCELLED");
                            break;
                        default:
                            break;
                    }
                    bool = false;
                }

                temp = temp.next;
            }

            if (bool) {
                JOptionPane.showMessageDialog(this, "Order ID not found");
                txtOrderID.setText("B");
            }
        }

    }//GEN-LAST:event_txtOrderIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchOrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerIDSearch;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerNameSearch;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblQtySearch;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusSearch;
    private javax.swing.JLabel lblTotalSearch;
    private javax.swing.JLabel lblTotalText;
    private javax.swing.JTextField txtOrderID;
    // End of variables declaration//GEN-END:variables
}
