/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iHungryBurgerShop;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shameel Shajaad
 */
public class UpdateOrderPage extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrderPage
     */
    private String ValidationOrderID;
    private boolean Validationcheck = false;

    public UpdateOrderPage() {
        initComponents();
        txtOrderID.setText("B");
        txtOrderID.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblTotalText = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        updateOrderBtn = new javax.swing.JButton();
        statusJComboBox = new javax.swing.JComboBox<>();
        txtCustomerID = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        orderExpJLabel1 = new javax.swing.JLabel();
        orderExpJLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 142, 126));

        lblHeader.setBackground(new java.awt.Color(255, 51, 51));
        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("UPDATE ORDER");
        lblHeader.setToolTipText("");
        lblHeader.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        lblOrderID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblOrderID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID.setText("Order ID :");

        lblCustomerID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblCustomerID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerID.setText("Customer ID :");

        txtOrderID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        txtOrderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrderIDKeyReleased(evt);
            }
        });

        cancelBtn = new RoundedButton("");
        cancelBtn.setBackground(new java.awt.Color(255, 51, 51));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Back");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQty.setText("Burger QTY :");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Order Status :");

        lblTotalText.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblTotalText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalText.setText("Total :");

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerName.setText("Customer Name :");

        updateOrderBtn = new RoundedButton("");
        updateOrderBtn.setBackground(new java.awt.Color(51, 255, 51));
        updateOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        updateOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateOrderBtn.setText("Update Order");
        updateOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderBtnActionPerformed(evt);
            }
        });

        statusJComboBox.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        statusJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preparing", "Delivered", "Cancelled" }));
        statusJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusJComboBoxActionPerformed(evt);
            }
        });

        txtCustomerID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        txtCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerIDKeyReleased(evt);
            }
        });

        txtCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N

        txtQty.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        orderExpJLabel1.setForeground(new java.awt.Color(255, 51, 51));
        orderExpJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        orderExpJLabel1.setToolTipText("");

        orderExpJLabel2.setForeground(new java.awt.Color(255, 51, 51));
        orderExpJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblTotal.setBackground(new java.awt.Color(241, 242, 242));
        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 51, 51));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(updateOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderID)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerID)
                    .addComponent(lblCustomerName)
                    .addComponent(lblQty)
                    .addComponent(lblTotalText))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCustomerID)
                            .addComponent(statusJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOrderID)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderExpJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(orderExpJLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderExpJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderExpJLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(statusJComboBox))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void updateOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderBtnActionPerformed
        if (Validationcheck) {
            if ((txtCustomerID.getText()).length() != 10) {
                JOptionPane.showMessageDialog(this, "Customer ID must include 10 digits");
                txtCustomerID.requestFocus();
            }
            int res = JOptionPane.showConfirmDialog(this, "Do you want to Update ? ", "Update Order", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {

                Node temp = HomePage.first;

                while (temp != null) {
                    if (ValidationOrderID.equals(temp.order.getBurgerID())) {
                        String customerID = txtCustomerID.getText();
                        String customerName = txtCustomerName.getText();
                        int qty = Integer.parseInt(txtQty.getText());
                        double total = Double.parseDouble(lblTotal.getText());
                        int status = statusJComboBox.getSelectedIndex();

                        temp.order.setCustomerID(customerID);
                        temp.order.setCustomerName(customerName);
                        temp.order.setBurgerQty(qty);
                        temp.order.setTotal(total);
                        temp.order.setStatus(status);
                    }
                    temp = temp.next;
                }

                JOptionPane.showMessageDialog(this, "Order Updated");

                txtOrderID.setText("B");
                txtCustomerID.setText("");
                txtCustomerName.setText("");
                txtQty.setText("");
                lblTotal.setText("0");

            } else {
                JOptionPane.showMessageDialog(this, "Order did not updated");

                txtOrderID.setText("B");
                txtCustomerID.setText("");
                txtCustomerName.setText("");
                txtQty.setText("");
                lblTotal.setText("0");
            }
        }
    }//GEN-LAST:event_updateOrderBtnActionPerformed

    private void statusJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusJComboBoxActionPerformed

    private void txtOrderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrderIDKeyReleased
        String orderID = txtOrderID.getText();

        if ((orderID.charAt(0)) != 'B') {
            JOptionPane.showMessageDialog(this, "Order ID must start with 'B'");
            txtOrderID.setText("B");
            return;
        }
        if (orderID.length() > 5) {
            JOptionPane.showMessageDialog(this, "Invalid Order ID length");
            txtOrderID.setText("B");
            return;
        }

        if (orderID.length() == 5) {
            statusJComboBox.setEnabled(true);
            orderExpJLabel1.setText("");
            orderExpJLabel2.setText("");
            txtCustomerID.setEditable(true);
            txtCustomerName.setEditable(true);
            txtQty.setEditable(true);

            Node temp = HomePage.first;
            boolean bool = true;

            while (temp != null) {
                if (orderID.equals(temp.order.getBurgerID())) {
                    ValidationOrderID = temp.order.getBurgerID();
                    Validationcheck = true;
                    txtCustomerID.setText(temp.order.getCustomerID());
                    txtCustomerName.setText(temp.order.getCustomerName());
                    txtQty.setText(Integer.toString(temp.order.getBurgerQty()));
                    double qty = temp.order.getBurgerQty();
                    lblTotal.setText(Double.toString(qty * 500));
                    if (temp.order.getStatus() == 0) {
                        statusJComboBox.setSelectedIndex(0);
                    } else if (temp.order.getStatus() == 1) {
                        statusJComboBox.setSelectedIndex(1);
                        statusJComboBox.setEnabled(false);
                        orderExpJLabel1.setText("This Order has been Delivered");
                        orderExpJLabel2.setText("Sorry, you cannot Update this Order");
                        txtCustomerID.setEditable(false);
                        txtCustomerName.setEditable(false);
                        txtQty.setEditable(false);
                    } else if (temp.order.getStatus() == 2) {
                        statusJComboBox.setSelectedIndex(2);
                        statusJComboBox.setEnabled(false);
                        orderExpJLabel1.setText("This Order has been Cancelled");
                        orderExpJLabel2.setText("Sorry, you cannot Update this Order");
                        txtCustomerID.setEditable(false);
                        txtCustomerName.setEditable(false);
                        txtQty.setEditable(false);
                    }
                    bool = false;
                    break;
                }

                temp = temp.next;
            }

            if (bool) {
                JOptionPane.showMessageDialog(this, "Order ID not found");
                txtOrderID.setText("B");
            }
        }
    }//GEN-LAST:event_txtOrderIDKeyReleased

    private void txtCustomerIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIDKeyReleased
        String text = txtCustomerID.getText();
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Customer ID cannot be empty");
        } else {
            char ch = txtCustomerID.getText().charAt(0);
            if (ch != '0') {
                JOptionPane.showMessageDialog(null, "Customer ID must start with a '0'");
                txtCustomerID.setText("0");
            }
            if (text.length() > 10) {
                JOptionPane.showMessageDialog(null, "Invalid Customer ID");
                txtCustomerID.setText("0");
            }
        }

        if (text.length() == 10) {
            txtCustomerName.requestFocus();
        }
    }//GEN-LAST:event_txtCustomerIDKeyReleased

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        String text = txtQty.getText();
        char ch = 0;
        boolean check = true;
        if (text.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Quantity cannot be empty");
            check = false;
        } else {
            for (int i = 0; i < text.length(); i++) {
                ch = txtQty.getText().charAt(i);
                if (ch < '0' || ch > '9') {
                    JOptionPane.showMessageDialog(this, "Cannot enter letteres or symbols in Quantity field");
                    txtQty.setText("");
                    check = false;
                }
            }
            if (check) {
                double qty = Double.parseDouble(txtQty.getText());
                if (qty <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantity must be greater than 0");
                } else {
                    lblTotal.setText(Double.toString(qty * 500));
                }
            }
        }
    }//GEN-LAST:event_txtQtyKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateOrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalText;
    private javax.swing.JLabel orderExpJLabel1;
    private javax.swing.JLabel orderExpJLabel2;
    private javax.swing.JComboBox<String> statusJComboBox;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQty;
    private javax.swing.JButton updateOrderBtn;
    // End of variables declaration//GEN-END:variables
}
